repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    sha: v1.1.3
    hooks:
    -   id: python-safety-dependencies-check